### ISSUE TITLE
Feature request: ability to stop the pagination based on Time

### ISSUE THREAD

**Issue by NorseGaud** [gofri/go-github-pagination#10]
Here is an example (ignore ExecuteGitHubClientFunction, it's used for my custom rate limiting):

```
var allHooks []github.HookDelivery
opts := &github.ListCursorOptions{PerPage: 10}
for {
	serviceCtx, hooks, response, err := ExecuteGitHubClientFunction(serviceCtx, logger, func() (*[]*github.HookDelivery, *github.Response, error) {
		hooks, response, err := githubClient.Repositories.ListHookDeliveries(serviceCtx, service.Owner, service.Repo, service.HookID, opts)
		if err != nil {
			return nil, nil, err
		}
		return &hooks, response, nil
	})
	if err != nil {
		logger.ErrorContext(serviceCtx, "error listing hooks", "err", err)
		return
	}
	for _, hook := range *hooks {
		allHooks = append(allHooks, *hook)
	}
	if response.Cursor == "" || (firstQueuedJobStartedAtDate.After(allHooks[len(allHooks)-1].DeliveredAt.Time)) {
		fmt.Println("breaking")
		break
	}
	opts.Cursor = response.Cursor
}
```

As you can see, the two conditions are Cursor being empty, or `(firstQueuedJobStartedAtDate.After(allHooks[len(allHooks)-1].DeliveredAt.Time)`, which is the eldest webhook I have received that I need to check for completed deliveries for. Ultimately this code helps me catch up after a webhook capture service being down and not getting "completed" workflow_job hooks.

It would be nice if `go-github-pagination` also supported this type of breaking of the pagination, so I save on api calls.

**Comment by gofri** [comment]
hey @NorseGaud,
I'm not sure that I really want to add custom hooks into the logic of the paginator.
You can solve this case in one of two ways:
1. Implement a custom [Driver](https://github.com/gofri/go-github-pagination/blob/main/githubpagination/drivers/driver.go) with your logic. The most straightforward way is probably to use the SyncDriver and add your logic around it.
2. Implement a custom HTTP RoundTripper and use it as the paginator's Base and implement the logic there (either return a bad response or modify the response headers).
I hope that helps

**Comment by NorseGaud** [comment]
Ultimately doesn't matter because I can't use this due to https://github.com/gofri/go-github-pagination/issues/9
