### ISSUE TITLE
[Bug] RoundTripper errors on `Issues.Get` EOF

### ISSUE THREAD

**Issue by danriedl** [gofri/go-github-pagination#2]
Hey.

I did encounter a problem yesterday, and I'm not certainly sure where it's coming from.
To reproduce, one can change the owner/repo to an issue in another repo.
```go
package main

import (
	"context"
	"log"

	"github.com/gofri/go-github-pagination/github_pagination/github_pagination"
	gh "github.com/google/go-github/v58/github"
)

var ctx = context.Background()
var paginator = github_pagination.NewGithubPaginationClient(nil)
var c = gh.NewClient(paginator).WithAuthToken("")

func main() {
	_, _, err := c.Issues.Get(ctx, "gofri", "go-github-pagination", 1)
	log.Fatal(err)
}
```

```text
2024/02/04 21:12:58 RoundTripper returned a response & error; ignoring response
2024/02/04 21:12:58 Get "https://api.github.com/repos/gofri/go-github-pagination/issues/1": EOF
exit status 1
```

**Comment by gofri** [comment]
thanks! I'm gonna investigate and update.
edit: ok, I figured out the issue, that was real stupid of me (it doesn't work for any non-paginated endpoint).
working on a fix :)

**Comment by gofri** [comment]
@danriedl done :)
I don't have the time to add unit testing for it now, but v0.1.1 should work for you :)
